services:
  - type: web
    name: bioscan
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gthread --workers 1 --threads 4 --timeout 120
    envVars:
      - key: CLIENT_CAMERA
        value: "true"
      - key: MAX_FRAME_WIDTH
        value: "512"
      - key: OUTPUT_JPEG_QUALITY
        value: "65"
      - key: ENABLE_TENSOR_MESH
        value: "false"
